Error msg for match undefined
npm/cli pull request #1009
Opened 2020-03-11 19:04 UTC by danielleadams

# What / Why
There's a bug in which an npm command will raise an error `Cannot run .match on undefined` and exit the script with an error. There are a few open issues:
- https://github.com/npm/cli/issues/973 (occurs with `npm install`)
- https://github.com/npm/cli/issues/961 (occurs with `npm install`)
- https://github.com/npm/cli/issues/703 (occurs with `npm audit fix`)
- https://github.com/npm/cli/issues/403 (occurs with `npm uninstall --save-dev`)

I've run into this with `npm prune`, but I was unable to reproduce it while looking into it. This doesn't fix the root of the issue, which it appears that empty parameters are being generated in the lock file something like this:

```
"package-a": {
  "dependencies": {
    "package-b": {}
  }
}
```

And causing an undefined error here: https://github.com/npm/cli/blob/latest/lib/install/inflate-shrinkwrap.js#L87

Because there is no `"version"` key that is passed in here: https://github.com/npm/cli/blob/latest/lib/install/inflate-shrinkwrap.js#L99 (which is returning an `undefined`.

## Solution
This catches a dependency if it's empty and displays an error message to the user to regenerated the package-lock.json or npm-shrinkwrap.json.

## References

* n/a

2020-04-03 18:30 UTC, ruyadorno approved these changes
awesome! 🎉 thanks @danielleadams

2020-06-10 21:22 UTC, ruyadorno commented
Sorry for the delay @danielleadams I was meant to write back to you after the last release - I tried landing this in `v6.14.5` but found out that there's some broken tests, basically it seems like the commit got the green light because CI just skipped all tests last time 😭

2020-06-10 21:26 UTC, ruyadorno commented on lib/install/inflate-shrinkwrap.js
> +      return errorHandler(message)
I believe you're going to have to return a `Promise` here in order to not break the promise chain, maybe simply?

```diff
-      return errorHandler(message)
+      return Promise.reject(errorHandler(message))
```

2020-06-10 21:27 UTC, ruyadorno requested changes
Tests are currently failing

2020-06-10 21:28 UTC, ruyadorno commented
btw, if you rebase on top of current `latest` branch it should fix the problem with CI 😊

2020-06-10 21:34 UTC, danielleadams commented
oh whoops! Ok.. let me rebase and see if it fixes, or otherwise fix it.

2020-06-11 22:33 UTC, ruyadorno approved these changes
awesome 🎉 thanks again @danielleadams 😊

2020-06-11 23:30 UTC, ruyadorno requested changes
digging a bit more into the output from each of the CI targets, there's actually a bunch of silent failures in the form of:

```
 npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\npm\cache\_logs\2020-06-11T20_02_29_720Z-debug.log
```

which seems to imply the broken chain of promise is still an issue 😞

2020-07-08 21:30 UTC, danielleadams commented
@ruyadorno I made changes to how errors are handling... instead of importing and using the error handler, I returned a failed promise with an error from the if statement. The tests pass, which tells me that the error is passed up the call stack and still handled. Let me know what you think 👍

2020-07-21 17:24 UTC, ruyadorno approved these changes

2020-07-21 20:25 UTC, closed without merging