npx: add install prompt, handle options correctly
npm/cli pull request #1596
Opened 2020-07-31 22:02 UTC by isaacs

- handle previous npx options that are still possible to be handled, and
  print a warning if any deprecated/removed options are used.
- expand shorthands properly in npx command line.
- take existing npm options into account when determining placement of
  the -- argument.
- document changes from previous versions of npx.

2020-08-03 15:01 UTC, ruyadorno requested changes

2020-08-03 15:01 UTC, ruyadorno commented on bin/npx-cli.js
> +  'shell-auto-feedback'
ooops, isn't it `shell-auto-fallback` ?

2020-08-03 15:01 UTC, ruyadorno commented on bin/npx-cli.js
> +      console.error(`npx: the --${key} argument has been removed.`)
I think it would be nice to have a more elaborate msg for some of these keys, or maybe just add a link to `npm help exec` (showing the "Compatibility with Older npx Versions" section) or to a blog post that explains the reasoning for the changes? as an user I would def appreciate that

2020-08-04 01:24 UTC, isaacs commented on bin/npx-cli.js
> +  'shell-auto-feedback'
good catch!

2020-08-04 04:38 UTC, closed without merging