Use @npmcli/run-script for exec, explore; add interactive exec
npm/cli pull request #2202
Opened 2020-11-19 19:33 UTC by isaacs

This removes all other arg/shell escaping mechanisms, as they are no
longer needed, and will be un-done by puka in @npmcli/run-script anyway.

Adds an interactive shell mode when `npm exec` is run without any
arguments, allowing users to interactively test out commands in an npm
script environment.  Previously, this would do nothing, and just exit.

Prevent weird behavior from `npm explore ../blah`.  `explore` now can
_only_ be used to explore packages that are actually found in the
relevant `node_modules` folder.

## References

2020-11-20 07:40 UTC, ljharb commented
Can the `npm exec` shell "not do that" in a non-TTY?

2020-11-24 18:21 UTC, darcyclarke requested changes
As per @ljharb's note, I think it would be good if we ensured this interactive mode wasn't something that could trip up CI environments... I've suggested two changes that should support that.

2020-11-24 18:21 UTC, darcyclarke commented on lib/exec.js
> +  if (!call && !args.length && !packages.length) {
```suggestion
  if (!call && !args.length && !packages.length && !isTTY && !ciDetect()) {
```

2020-11-24 18:21 UTC, darcyclarke commented on docs/content/commands/npm-exec.md
> +`package.json` scripts are run.
```suggestion
`package.json` scripts are run; Only available in TTY/non-CI environments.
```

2020-11-24 18:27 UTC, darcyclarke commented on lib/exec.js
>  const cmd = (args, cb) => exec(args).then(() => cb()).catch(cb)
```suggestion
      const isTTY = process.stdin.isTTY && process.stdout.isTTY
```

2020-11-24 18:40 UTC, isaacs commented
Hm, if stdin is not a TTY, then it just means it'll read from whatever it _is_, and close when it closes.

```
$ echo 'echo $npm_package_name' > cmd

$ node . exec < cmd

Entering npm script environment
Type 'exit' or ^D when finished

npm
```

But, yes, if it's CI and it _is_ a TTY, we should not do that.  And if it's not a TTY, we should probably not show the helpful help banner.

2020-11-24 18:45 UTC, isaacs commented
So, wait, if it _is_ in CI, and we abort, that means you can't run commands from stdin in CI, which seems like a suboptimal situation?  What if you have a bunch of shell commands in a file, and want to run `npm exec < file.sh` in CI?

I think the only situation we should exit early in is if it's CI _and_ a TTY, with a warning that we're doing so.

2020-11-24 20:19 UTC, isaacs commented
Updated with the logic described.  Also simplified some of the `isTTY` checking, since it's really only `stdin` that we care about there.  (If someone pipes the command to `| tee output.log`, then we should still behave the same way, since it's _input_ availability that is relevant when prompting, but if you `cat commands.sh | npm exec`, then it should Just Work, and not give you a surprise prompt.)

2020-12-02 21:08 UTC, darcyclarke approved these changes
✅ LGTM

2020-12-04 19:17 UTC, merged