test: replace requireInject with t.mock tap api
npm/cli pull request #2370
Opened 2020-12-17 05:26 UTC by ruyadorno

- Replaces all usage of `requireInject` with `t.mock`
- Standardizes usage of tap as: `const t = require('tap')`
- Fixes some rare cases in which mocks were relying in the fact that
`requireInject` placed mocks within the `require.cache` and made mocks
available for nested files, this type of scenario now requires an extra
`t.mock` declaration in order to define mocks to that nested file.

2020-12-18 19:17 UTC, darcyclarke requested changes
**Blocked:** Need to land the change in `tap` first & then update the dep in `package.json`

2021-02-13 08:11 UTC, darcyclarke commented
@ruyadorno we **need** to land this. @isaacs I'm willing to commit resources to get [this](https://github.com/tapjs/node-tap/pull/698) across the finish line next week, unless you've got any reservations about landing it. I know It probably means cutting a minor of `tap` but I don't know what the blocker has been other than just getting time to do that - maybe we can get more resources dedicated to `tap` moving forward(?) ~ especially given that we rely on it so heavily throughout the CLI

2021-02-25 16:58 UTC, ruyadorno commented
We need to update to **tap@15** (not yet released at this point in time) and do a second pass of updating all test files, fixing conflicts and migrating new instances of `require-inject` usage.

I'm removing the `Release-Next` label to better reflect the current state.

2021-04-14 16:44 UTC, wraithgar commented
Woohoo! This got done in #3069

2021-04-14 16:44 UTC, closed without merging

2021-04-14 16:46 UTC, ruyadorno commented
🥳