fix(docs): clean up `npm search` docs
npm/cli pull request #2487
Opened 2021-01-13 17:30 UTC by wraithgar

In which the "note on caching" is finally populated after
all these years

## References
Closes https://github.com/npm/statusboard/issues/243

2021-01-13 18:01 UTC, npm-deploy-user commented
no statistically significant performance changes detected

<details><summary>timing results</summary>

|**app-large**|clean|lock-only|cache-only|cache-only<br/>legacy-peer-deps|modules-only|no-lock|no-cache|no-modules|no-clean|no-clean<br/>audit|
|---|---|---|---|---|---|---|---|---|---|---|
|npm@7|50.060 ±0.36|32.010 ±0.10|31.423 ±0.53|28.460 ±1.33|2.436 ±0.03|2.444 ±0.03|1.681 ±0.04|12.347 ±0.05|1.696 ±0.04|3.879 ±0.09|
|#2487|52.888 ±3.21|31.282 ±0.17|33.894 ±1.75|30.508 ±0.12|2.413 ±0.01|2.377 ±0.10|1.706 ±0.01|12.449 ±0.03|1.704 ±0.05|3.880 ±0.18|

|**app-medium**|clean|lock-only|cache-only|cache-only<br/>legacy-peer-deps|modules-only|no-lock|no-cache|no-modules|no-clean|no-clean<br/>audit|
|---|---|---|---|---|---|---|---|---|---|---|
|npm@7|35.923 ±0.02|22.736 ±0.20|22.136 ±0.50|20.698 ±0.28|2.353 ±0.00|2.315 ±0.03|1.610 ±0.04|7.855 ±0.20|1.607 ±0.01|3.533 ±0.32|
|#2487|36.240 ±0.07|22.471 ±0.06|25.378 ±3.74|21.990 ±0.65|2.335 ±0.12|2.409 ±0.07|1.615 ±0.02|7.989 ±0.00|1.603 ±0.06|3.495 ±0.59|
</details>

2021-01-14 20:00 UTC, darcyclarke requested changes

2021-01-14 20:00 UTC, darcyclarke commented on docs/content/commands/npm-search.md
> +metadata for all files in the registry. If your terminal has color
I believe this may be referring to the config [`color`](https://docs.npmjs.com/cli/v6/using-npm/config#color) which I'm not sure about whether terminals set that in the env; Obviously, this statement may still be true in either case.

2021-01-14 20:00 UTC, darcyclarke commented on docs/content/commands/npm-search.md
> +the cli uses this cache. See [npm cache](/commands/npm-cache) for more
```suggestion
the cli uses this cache. See [`npm cache`](/commands/npm-cache) for more
 ```

2021-01-14 20:47 UTC, wraithgar commented on docs/content/commands/npm-search.md
> +metadata for all files in the registry. If your terminal has color
This needs to be completely rewritten then cause it's very ambiguous.

2021-01-14 21:07 UTC, darcyclarke approved these changes

2021-01-14 22:14 UTC, closed without merging