elaborate that npm help uses browser
npm/cli pull request #2502
Opened 2021-01-16 22:33 UTC by ariccio

As I mentioned in issue #2501 it is is mildly annoying to me that I forget that the npm help command opens a browser, and probably a few other people.  

I have added "(in a browser)" to the npm usage string at the npm help line. Is this a reasonable change? It makes the output slightly more verbose, but reduces the occasional surprise of opening a browser with a saved session of over 900 tabs just to view a single help page. Yes, really, I do have 1004 tabs open currently, and that's an outlier, but I'm sure this impacts other people in less unusual circumstances.

## References

Fixes #2501

2021-01-19 18:40 UTC, wraithgar commented
`npm help` only opens in a browser (by default) on windows, because there is no `man` command in windows.  This is driven by the config value of `viewer` which is set to `browser` in windows, and `man` in osx and linux.

At the very least we would want to make sure to indicate that this is only the default in windows. Not sure how to do that succinctly off the top of my head.

2021-01-19 18:42 UTC, ljharb commented
@wraithgar maybe include `npm config get viewer` dynamically in the help output?

2021-01-21 16:27 UTC, ruyadorno requested changes
We already have this explained as part of `npm help help`.

We can not land this as-is for the reasons @wraithgar just mentioned but maybe it's worth exploring the solution from @ljharb, I'm not 100% sure about having a conditional in usage messages but if that's feasible then it may even keep this ` (in a browser)` value in windows-only.

2021-01-21 18:47 UTC, ariccio commented
It might be very reasonable to display this on windows only! I like that idea, but (of course) that makes this a non-trivial change. What's the best way to do that?

2021-01-21 18:56 UTC, wraithgar commented
I believe that when this file is loaded the config is already loaded. You could gate the extra output behind a conditional that checks if viewer is set to browser.

2021-01-21 23:22 UTC, ljharb commented
This approach has the benefit of matching "the current config", including if a user overrode it.

2021-02-01 20:57 UTC, closed without merging