pass -q to curl calls to disable user .curlrc files
npm/cli pull request #2613
Opened 2021-02-03 21:01 UTC by nlf

this will make the install.sh script a little easier for any users who happen to have a `.curlrc` that alters the default behavior in a way we do not expect

## References

Related to https://github.com/npm/cli/issues/2599#issuecomment-772789383

2021-02-03 22:25 UTC, wraithgar requested changes
We may as well make the example in the readme match this too or else they'll never GET to this point if this is a problem.

2021-02-03 22:29 UTC, ljharb approved these changes
<3 ty (including the readme change)

2021-02-04 15:33 UTC, nlf commented
tweaked the README too

2021-02-04 15:42 UTC, wraithgar approved these changes

2021-02-04 23:10 UTC, merged