fix(npx): use proper cache param
npm/cli pull request #3430
Opened 2021-06-16 20:33 UTC by wraithgar

The `flatOptions` cache is the one that is intended to be passed down
into other modules, as it has the `_cacache` suffix attached.  What was
happening before was that `npx` was creating a new alternate cache one
directory up from where everything else was, and also putting the `_npx`
content there.  It is possible this is the source of at least some of
our "npx doesn't find the right versions" bugs.

2021-06-16 20:35 UTC, wraithgar commented
Test changes fail before the fix was implemented and pass with it implemented.

2021-06-17 14:32 UTC, ruyadorno requested changes
I know at least `libnpmexec` is expecting `cache` to be up a level: https://github.com/npm/libnpmexec/blob/5dcbb9a28200f13037a0190843337b0159533890/lib/cache-install-dir.js

let's make sure to fix it there first in case we want to land this one

2021-06-17 14:35 UTC, ruyadorno commented
I mean, assuming the intent was to have `npm exec` placing things at `~/.npm/_npx` instead of `~/.npm/_cacache/_npx` - but that assumption might be wrong

2021-06-17 14:47 UTC, wraithgar commented
libnpmexec expects it to be in BOTH places, because it passes it down into pacote which expects that value to be the "cacache" cache option:

https://github.com/npm/libnpmexec/blob/ac28b80f1a6e3b51fa19a155cb46dd5c57fe8cc0/lib/index.js#L106-L110

2021-06-17 15:01 UTC, ruyadorno commented
> libnpmexec expects it to be in BOTH places, because it passes it down into pacote which expects that value to be the "cacache" cache option:
> 
> https://github.com/npm/libnpmexec/blob/ac28b80f1a6e3b51fa19a155cb46dd5c57fe8cc0/lib/index.js#L106-L110

😱

2021-06-17 15:25 UTC, ruyadorno approved these changes
LGTM 👍

2021-06-17 15:30 UTC, merged