docs: add --dry-run to npm install
npm/cli pull request #41
Opened 2018-08-08 03:39 UTC by reconbot

2018-08-09 00:03 UTC, zkat requested changes
This looks good. I'd really like this to be added to the `npm pack` docs, since they both support `--dry-run` now. Do you mind doing that?

2018-08-13 21:10 UTC, zkat approved these changes
Looks good! Thanks!

2018-08-14 00:47 UTC, styfle approved these changes

2018-08-20 22:27 UTC, zkat approved these changes
Thank you! This looks great. I really hope it helps more people learn about `--dry-run` on these two commands, which is super handy sometimes 👍

2018-08-20 22:28 UTC, merged