fix(arborist): shrinkwrap throws when trying to read a folder without permissions
npm/cli pull request #4258
Opened 2022-01-18 23:03 UTC by Linkgoron

This PR fixes a minor regression [introduced here](https://github.com/npm/arborist/pull/244/files#diff-1890f8f0aa793214ab66b5dfe13943c748ef142aea5d10d9b8ace12a65a092b8R421) where `Shrinkwrap.load` throws an error instead of returning correctly when arborist doesn't have access to the folder it's trying to read.

The issue is caused by trying to log `const rel = relpath(this.path, this.filename)` when `this.filename` is null. `this.filename` is set after `this[_maybeRead]()` executes, but when there are permission issues `this[_maybeRead]()` throws, and `this.filename` stays `null`, and `relpath` (and consequentially, `load`) throws `The "to" argument must be of type string` error.

I've changed the code to only execute `relpath` if `this.filename` is set correctly.

2022-01-19 01:28 UTC, Linkgoron commented
I assume that chmod is not working correctly on windows, should I skip the test on windows, or change the tests to use something like icacls?

2022-01-20 20:19 UTC, ruyadorno requested changes
thanks @Linkgoron 😄 I believe it's going to be a simpler and easier to maintain in the long term test if we just skip windows for now

2022-01-20 20:19 UTC, ruyadorno commented on workspaces/arborist/test/shrinkwrap.js
> +
```suggestion
```

this does not look like the most reliable thing to me, if we don't have an api in node to set these permission I'd rather skip the test in that case

2022-01-20 20:19 UTC, ruyadorno commented on workspaces/arborist/test/shrinkwrap.js
> +      }
```suggestion
      fs.chmodSync(dir, '666')
```

same

2022-01-20 20:19 UTC, ruyadorno commented on workspaces/arborist/test/shrinkwrap.js
> +  })
```suggestion
  }, { skip: process.platform === 'win32' ? 'skip chmod in windows' : false)
```

let's skip the test in windows instead

2022-01-20 21:02 UTC, Linkgoron commented on workspaces/arborist/test/shrinkwrap.js
> +
Done, although I couldn't get the linter to work so I assume that I'll need to fix that.

2022-01-21 13:41 UTC, Linkgoron commented on workspaces/arborist/test/shrinkwrap.js
> +
@ruyadorno I've added the skip, but now the coverage is lower than 100% and the workflow fails. Should I add `/* istanbul ignore next */` or something?

2022-01-26 20:46 UTC, ruyadorno approved these changes
LGTM 👍

2022-01-26 20:59 UTC, merged