deps: npm-registry-fetch
npm/cli pull request #4326
Opened 2022-01-25 19:20 UTC by wraithgar

- deps: pacote@12.0.3
- deps: npm-profile@6.0.0
- deps: npm-registry-fetch@12.0.1

2022-01-25 23:00 UTC, ruyadorno requested changes
just take a look to confirm but it seems to me that these are unwanted deps popping up on arborist, otherwise the rest of updates looks fine 👍

2022-01-25 23:00 UTC, ruyadorno commented on workspaces/arborist/package.json
> +    "libnpmteam": "^3.0.0",
are these expected? it looks to me like it might be something wrong going on here 👀

2022-01-25 23:00 UTC, ruyadorno commented on package-lock.json
> +        "libnpmteam": "^3.0.0",
it shows up here too ☝️

2022-01-26 14:52 UTC, wraithgar commented on workspaces/arborist/package.json
> +    "libnpmteam": "^3.0.0",
Yeah idk what went wrong here, it happened when I installed pacote which is a little worrying. I'm hoping I just typed something else somehow along the way?  We'll have to keep our eyes out for this in the future.

2022-01-26 20:50 UTC, ruyadorno approved these changes

2022-01-26 20:51 UTC, merged