pack: add dryRun option to packDirectory
npm/cli pull request #47
Opened 2018-08-14 13:40 UTC by larsgw

Add `dryRun` option to `packDirectory`. This makes it possible to run postscript after the archive has been written to cwd. Something similar could probably be done for `packFromPackage`.

See https://npm.community/t/592?u=larsgw

2018-08-15 17:24 UTC, zkat requested changes
Thank you! This is great. Could you add a small test to make sure the original problem isn't happening anymore with this change?

2018-08-15 21:58 UTC, larsgw commented
It's not the prettiest test: the error message doesn't really work, but I believe that's how `test/tap/lifecycle-order.js` does it.

2018-08-20 13:27 UTC, larsgw commented
@zkat, I don't think I can request another review with GitHubs interface, or respond to the first one, but I added a test.

2018-08-20 22:52 UTC, zkat approved these changes
Nice! Thanks a bunch. This is a great bug fix! 🎉

2018-08-20 22:53 UTC, merged