docs: name and version description change
npm/cli pull request #5753
Opened 2022-10-26 16:37 UTC by dominikgorczyca

Reducing redundancy by deleting repeated code and changing other slight things about those two fields.

2022-10-27 18:37 UTC, lukekarrys requested changes
Thank you for the PR! There's some ongoing discussion about how to handle the required-ness of `name` and `version`. I think there's a little more nuance than them being strictly required or optional. https://github.com/npm/documentation/pull/134

Can you update this PR to remove those parts of the changes?

2022-10-28 17:20 UTC, dominikgorczyca commented
Not sure if this is what you mean, but I changed some things about requiredness... Is there something else I should delete?

2022-10-28 19:50 UTC, lukekarrys approved these changes

2022-10-28 19:50 UTC, lukekarrys commented
Thanks for the updates! I think this looks good now.

2022-11-01 17:21 UTC, wraithgar commented on docs/content/configuring-npm/package-json.md
> +Put a description in it. It's a string.  This helps people discover your
```suggestion
Put a description in it.  It's a string.  This helps people discover your
```

2022-11-01 17:22 UTC, wraithgar commented on docs/content/configuring-npm/package-json.md
> +
```suggestion

```

2022-11-01 17:23 UTC, merged