Update npm-ci.md
npm/cli pull request #6156
Opened 2023-02-10 17:50 UTC by jasonnicholson

`.bin` is not deleted by `npm ci` in `node_modules`.

## References
none

2023-02-11 00:00 UTC, lukekarrys commented
I'm not sure that is accurate, but neither are the current docs.

The implementation is here: https://github.com/npm/cli/blob/1fa37f5567bf50fab24098ed6b584ee3647af88c/lib/commands/ci.js#L69-L70

`npm ci` doesn't delete the `node_modules/` directory, but will delete everything inside of it.

@jasonnicholson Two things:
- Can you show an example of when `npm ci` isn't deleting `node_modules/.bin`?
- Once we figure that out, I'd still be open to landing this PR to update the language to accurately reflect what `npm ci` is doing.

2023-02-11 00:01 UTC, lukekarrys requested changes
I'm not sure that is accurate, but neither are the current docs.

The implementation is here: https://github.com/npm/cli/blob/1fa37f5567bf50fab24098ed6b584ee3647af88c/lib/commands/ci.js#L69-L70

`npm ci` doesn't delete the `node_modules/` directory, but will delete everything inside of it.

@jasonnicholson Two things:
- Can you show an example of when `npm ci` isn't deleting `node_modules/.bin`?
- Once we figure that out, I'd still be open to landing this PR to update the language to accurately reflect what `npm ci` is doing.

2023-02-25 05:46 UTC, jasonnicholson commented
I work with npm 6 but not in the javascript/node ecosystem. At work, we have leveraged npm to manage our packages because our language doesn't have a package manager. We use a lot of binary calls in the postinstall script. What I have noticed is that the .bin folder is not deleted during an npm ci.

From investigating npm 9, it seems that .bin is deleted.

Where are the relevant lines of code for npm 6?

2023-02-25 05:48 UTC, jasonnicholson commented
As to an example for npm 6, I tried using preinstall script and postinstall script to show the state of node_modules, but the state look the same.

2023-02-27 10:29 UTC, jasonnicholson commented
I thought of a way of testing if the .bin folder is deleted during an `npm ci`. I create a file in the .bin folder and then checked if it  was deleted after calling `npm ci`. For npm@6.14.17, the file was not deleted implying the .bin folder was not deleted. For npm@9.5.0, the .bin folder is deleted. I stand by the modifications I made to the documentation for npm@6. 

Simple script:
```shell
npm -v
npm init -y
npm i pacakge_that_puts_something_in_.bin_folder
ls node_modules/.bin/
touch node_modules/.bin/_TEST_FILE
npm ci
ls node_modules/.bin/
```

2023-03-08 17:48 UTC, lukekarrys commented
> Note that this Pull Request is to update npm@6 documentation and not npm@9

Thank you for clarifying and for the PR. I did miss that during my initial review. `npm@6` is currently only released for security updates currently, so unfortunately we can't merge this PR even for a minor docs update.

2023-03-08 17:48 UTC, closed without merging