fix: update provenance transparency log link
npm/cli pull request #6287
Opened 2023-03-24 18:40 UTC by bdehamer

Updates the transparency log URL which is displayed when publishing a package with provenance. The new URL points to the Rekor search UI instead of the REST API.

## References

2023-03-24 19:21 UTC, bdehamer commented
/cc @feelepxyz @trevrosen

2023-03-24 19:42 UTC, feelepxyz approved these changes

2023-03-27 14:11 UTC, wraithgar commented
Are we not asserting this output anywhere?

2023-03-27 16:44 UTC, bdehamer commented
@wraithgar added a test asserting on the `log.notice` output

2023-03-27 17:47 UTC, wraithgar approved these changes

2023-03-27 17:49 UTC, wraithgar requested changes

2023-03-27 17:49 UTC, wraithgar commented on workspaces/libnpmpublish/test/publish.js
> +    'proc-log': { notice: (...msg) => log.push(['notice', ...msg]) },
https://github.com/npm/cli/blob/latest/test/lib/commands/ping.js#L6

2023-03-27 18:15 UTC, wraithgar approved these changes

2023-03-29 17:52 UTC, merged