add ps1 scripts
npm/cli pull request #6548
Opened 2023-06-09 11:27 UTC by mribbons

Resolves UNC path issues because powershell.exe
supports UNC, while cmd.exe doesn't.
(Which is why npm.cmd doesn't work within
UNC paths, even under powershell)

Added ps1 versions of npm and npx

Closes https://github.com/npm/cli/issues/6280

2023-06-15 20:15 UTC, lukekarrys commented
I'd like to get a better idea of how you are currently running these scripts on your system. You mention installing them here `$(Get-Command "npm").Source`, what directory is that on your machine? How have you previously installed Node on this machine (and npm if that was installed differently)?

This can be merged into `npm`, but I believe it will require coordination with Node in order for this to land and have it work when installing Node on Windows. Currently the Node Windows installers (of which I know very little about) reference `npm.cmd` in the locations below. I'm assuming something similar will need to be done with `npm.ps1` to have it work as expected in these system.

- [/tools/msvs/msi/nodemsi/product.wxs](https://github.com/nodejs/node/blob/d2dfdd654ecb9fe340c06a830546977029bf5150/tools/msvs/msi/nodemsi/product.wxs#L221-L235)
- [/tools/msvs/nodevars.bat](https://github.com/nodejs/node/blob/d2dfdd654ecb9fe340c06a830546977029bf5150/tools/msvs/nodevars.bat#L14)
- [/vcbuild.bat](https://github.com/nodejs/node/blob/d2dfdd654ecb9fe340c06a830546977029bf5150/vcbuild.bat#L426-L437)

@mribbons Would you be able to open an issue or PR on https://github.com/nodejs/node to get feedback on how the Windows installers work, and if it would be appropriate for `npm` to ship these `ps1` scripts in our `bin/` dir and have them picked up by the installer?

Also in the meantime, would shipping these scripts in the npm bin dir, even if they dont get linked via the Windows installer, fix #6280?

2023-06-15 20:20 UTC, lukekarrys commented
Also this will need to land with some tests in [`test/bin/windows-shims.js`](https://github.com/npm/cli/blob/latest/test/bin/windows-shims.js).

@mribbons If you want to attempt that, go for it. Otherwise I will work on those.

2023-06-15 20:21 UTC, lukekarrys requested changes, later dismissed
Requesting changes until we have feedback from Node and tests.

2023-06-16 00:14 UTC, mribbons commented
> @mribbons If you want to attempt that, go for it. Otherwise I will work on those.

I'll give it a shot!

2023-06-16 00:28 UTC, mribbons commented
@lukekarrys 
> what directory is that on your machine?

C:\Program Files\nodejs\npm.ps1

> How have you previously installed Node on this machine

Using `Windows Installer` from [node](https://nodejs.org/en/download)

> Would you be able to open an issue or PR

https://github.com/nodejs/node/issues/48471

> Also in the meantime, would shipping these scripts in the npm bin dir, even if they dont get linked via the Windows installer, fix [#6280](https://github.com/npm/cli/issues/6280)?

My guess is no, the new scripts probably won't be deployed by the installer.

Thanks for your help.

2023-06-23 04:44 UTC, lukekarrys commented
@mribbons I pushed a commit to this PR implementing tests for the powershell scripts you added.

I did make one minor change to the scripts to match the behavior of the other bin scripts, so they now run `node npm-cli.js prefix -g` to see if their is a symlinked npm that should be called instead.

I'm not sure if all the tests will pass cleanly here since I've been doing some Windows cleanup in #6586 that might need to merge first. But I tested the combination of that PR and this one on my local machine and it worked.

2023-06-23 04:48 UTC, mribbons commented
@lukekarrys You are the man, thankyou!

2023-06-23 23:28 UTC, lukekarrys commented
This has been rebased to include the changes from #6586 so that tests will pass. That PR will need to be merged first.

2023-06-26 14:35 UTC, merged

2025-05-01 16:43 UTC, alexsch01 commented
This caused https://github.com/cypress-io/cypress/issues/31616
Wish PowerShell would work in a mode that doesn't treat commas as making a list

2025-05-01 16:49 UTC, wraithgar commented
Folks are working on fixing this, started in https://github.com/npm/cli/pull/7458 and we're waiting on someone to pick up the last mile work.