fix: use includePrerelease flag when checking node version
npm/cli pull request #6574
Opened 2023-06-19 20:07 UTC by wraithgar

The code stripping it out predates that flag even existing in node-semver

2023-06-19 20:17 UTC, wraithgar commented
Gonna have to get clever in the test fixture

2023-06-19 23:20 UTC, lukekarrys requested changes

2023-06-19 23:20 UTC, lukekarrys commented on test/lib/cli-entry.js
> +  t.notMatch(logs.warn[0], [])
This asserts works, but I think it would be clearer if written as:
```suggestion
  t.strictSame(logs.warn[0], [])
```

2023-06-19 23:20 UTC, lukekarrys commented on lib/cli-entry.js
> +  if (!satisfies(validateEngines.node, validateEngines.engines, { includePrerelease: true })) {
This doesn't seem to work for the bottom of each comparator (`X.0.0`), eg:

```js
> satisfies('18.0.0', '^14.17.0 || ^16.13.0 || >=18.0.0', { includePrerelease: false })
true
> satisfies('18.0.0-pre.0', '^14.17.0 || ^16.13.0 || >=18.0.0', { includePrerelease: false })
false
```

2023-06-19 23:39 UTC, lukekarrys commented on lib/cli-entry.js
> +  if (!satisfies(validateEngines.node, validateEngines.engines, { includePrerelease: true })) {
I think this is an issue with our engines. They should probably be `^14.17.0 || ^16.13.0 || >=18`.

```
> satisfies('18.0.0-pre.0', '^14.17.0 || ^16.13.0 || >=18', { includePrerelease: true })
true
```

2023-06-20 01:26 UTC, lukekarrys commented on lib/cli-entry.js
> +  if (!satisfies(validateEngines.node, validateEngines.engines, { includePrerelease: true })) {
I created a template-oss PR to fix this implement this at the source:

https://github.com/npm/template-oss/pull/317

2023-06-20 13:48 UTC, wraithgar commented
https://nodejs.org/download/release/

Do we even need the flag at all?

2023-06-20 16:19 UTC, lukekarrys commented
> https://nodejs.org/download/release/
> 
> Do we even need the flag at all?

At the risk of prematurely optimizing, if Node ever did ship a prerelease we would want that flag (and the template-oss PR). So I think for the sake of having the code match our intent (even if it's not currently possible), we should land both PRs.

2023-06-20 16:55 UTC, lukekarrys approved these changes

2023-06-20 17:00 UTC, merged