chore(docs): update unpublish docs with both commands, removing policy info from cli docs, and added reference to unpublish policy docs
npm/cli pull request #730
Opened 2020-01-27 23:05 UTC by nomadtechie

- Updating docs unpublish docs to with examples of both unpublish commands
- Removing policy info from cli docs to centralize policy in policy docs
- Added reference to unpublish policy docs

2020-01-27 23:36 UTC, mikemimik requested changes
The small inclusion of the man pages notation.

As well as the update to the command usage (`lib/unpublish.js`):
```diff
- unpublish.usage = usage('npm unpublish [<@scope>/]<pkg>[@<version>]')
+ unpublish.usage = usage(
+   'unpublish',
+   '\nnpm unpublish [<@scope>/]<pkg>[@<version>]' +
+   '\nnpm unpublish [<@scope>/]<pkg> --force'
+ )
```

2020-01-27 23:36 UTC, mikemimik commented on docs/content/cli-commands/npm-unpublish.md
> +npm unpublish <package-name>@<version>
```suggestion
npm unpublish [<@scope>/]<pkg>@<version> [--force]
```

2020-01-27 23:36 UTC, mikemimik commented on docs/content/cli-commands/npm-unpublish.md
> +npm unpublish <package-name> -f
```suggestion
npm unpublish [<@scope>/]<pkg> --force
```

2020-01-27 23:52 UTC, npm-deploy-user commented
<table>
    <thead>
      <tr>
        <th></th>
        <th colspan="3">angular-quickstart</th>
<th colspan="3">app-large</th>
<th colspan="3">app-medium</th>
<th colspan="3">ember-quickstart</th>
<th colspan="3">react-app</th>
      </tr>
      <tr>
        <th></th>
        <th>prev</th>
<th>current</th>
<th>status</th>
<th>prev</th>
<th>current</th>
<th>status</th>
<th>prev</th>
<th>current</th>
<th>status</th>
<th>prev</th>
<th>current</th>
<th>status</th>
<th>prev</th>
<th>current</th>
<th>status</th>
      </tr>
    </thead>
    <tbody>
      <tr>
<td>initial install</td>
<td>41s</td>
<td>35.8s</td><td>✅</td>
<td>39.5s</td>
<td>33.5s</td><td>✅</td>
<td>34.5s</td>
<td>28.9s</td><td>✅</td>
<td>28.1s</td>
<td>23.3s</td><td>✅</td>
<td>33.5s</td>
<td>29.7s</td><td>✅</td>
</tr>
<tr>
<td>repeat install</td>
<td>9.6s</td>
<td>7.8s</td><td>✅</td>
<td>8.6s</td>
<td>6.7s</td><td>✅</td>
<td>8.3s</td>
<td>6.8s</td><td>✅</td>
<td>7.7s</td>
<td>6.1s</td><td>✅</td>
<td>9.1s</td>
<td>7.3s</td><td>✅</td>
</tr>
<tr>
<td>with warm cache</td>
<td>32.3s</td>
<td>26.8s</td><td>✅</td>
<td>33.8s</td>
<td>28.7s</td><td>✅</td>
<td>31.3s</td>
<td>29.3s</td><td>✅</td>
<td>23.4s</td>
<td>19.2s</td><td>✅</td>
<td>29.1s</td>
<td>26.2s</td><td>✅</td>
</tr>
<tr>
<td>with node_modules</td>
<td>9.2s</td>
<td>7.6s</td><td>✅</td>
<td>8.6s</td>
<td>6.5s</td><td>✅</td>
<td>9s</td>
<td>6.9s</td><td>✅</td>
<td>7.8s</td>
<td>6.1s</td><td>✅</td>
<td>9.4s</td>
<td>7.3s</td><td>✅</td>
</tr>
<tr>
<td>with lockfile</td>
<td>32.6s</td>
<td>24.9s</td><td>✅</td>
<td>31s</td>
<td>28.3s</td><td>✅</td>
<td>29s</td>
<td>25.4s</td><td>✅</td>
<td>21.7s</td>
<td>17.3s</td><td>✅</td>
<td>27.4s</td>
<td>21.3s</td><td>✅</td>
</tr>
<tr>
<td>with warm cache and node_modules</td>
<td>9.3s</td>
<td>9s</td><td>✅</td>
<td>7.9s</td>
<td>6.1s</td><td>✅</td>
<td>8.4s</td>
<td>8.1s</td><td>✅</td>
<td>7.6s</td>
<td>6.8s</td><td>✅</td>
<td>9.2s</td>
<td>7.3s</td><td>✅</td>
</tr>
<tr>
<td>with warm cache and lockfile</td>
<td>24.7s</td>
<td>20.8s</td><td>✅</td>
<td>26.3s</td>
<td>23.5s</td><td>✅</td>
<td>24.3s</td>
<td>18.5s</td><td>✅</td>
<td>17.8s</td>
<td>14.3s</td><td>✅</td>
<td>21.3s</td>
<td>18.8s</td><td>✅</td>
</tr>
<tr>
<td>with node_modules and lockfile</td>
<td>10.1s</td>
<td>9.4s</td><td>✅</td>
<td>9.8s</td>
<td>7s</td><td>✅</td>
<td>8.6s</td>
<td>7.6s</td><td>✅</td>
<td>7.8s</td>
<td>6.3s</td><td>✅</td>
<td>9.7s</td>
<td>7.9s</td><td>✅</td>
</tr>
    </tbody>
  </table>

2020-01-28 17:00 UTC, mikemimik commented
Note: will be moving this from [Sprint 2](https://github.com/npm/cli/milestone/3) -> [Sprint 3](https://github.com/npm/cli/milestone/4) and rolled into the next release.

2020-02-25 19:43 UTC, darcyclarke commented
@nomadtechie noticed this got missed from our latest release & we figured out why; This PR has failing tests so it was skipped in the triage last week. Apologies for that. If we can fix whatever the issues are w/ linting/test coverage we'll pull this in next.

2020-02-25 21:31 UTC, nomadtechie commented
> @nomadtechie noticed this got missed from our latest release & we figured out why; This PR has failing tests so it was skipped in the triage last week. Apologies for that. If we can fix whatever the issues are w/ linting/test coverage we'll pull this in next.

lint error is resolved now - thanks again @darcyclarke !

2020-03-03 18:42 UTC, closed without merging