Add support for time-traveling installs.
npm/cli pull request #90
Opened 2018-10-31 03:14 UTC by zkat

2018-11-01 18:00 UTC, iarna requested changes

2018-11-01 18:00 UTC, iarna commented on doc/misc/npm-config.md
> +### enjoy-by
As mentioned on Twitter, this does also need a more straightforward name, especially for non-English speakers.

2018-11-01 18:00 UTC, iarna commented on lib/install.js
> +  if (npm.config.get('enjoy-by')) {
This does have potentially interesting interactions with lock files, which is to say, I'm not sure it does anything in the presence of a valid lock file. We should probably warn in that scenario, as otherwise we're setting up a foot gun.

2018-11-01 21:51 UTC, zkat commented on doc/misc/npm-config.md
> +### enjoy-by
Oh I forgot to push the commit. I aliased it to `--before`.

2018-11-01 21:52 UTC, zkat commented on doc/misc/npm-config.md
> +### enjoy-by
I almost did `--published-by`, but after seeing it, realized it looked like it wanted a maintainer name, not a timestamp.

2018-11-08 14:30 UTC, Grawl commented
just like [`npm-time-machine`](https://www.npmjs.com/package/npm-time-machine), awesome!

just tried `ntm` on [`youknowriad/standalone-gutenberg`](https://github.com/youknowriad/standalone-gutenberg). `Wordpress/gutenberg` was no version, and `ntm` return `null` for it :\ I expected `9ebb918176c1efd0c41561d67ea3273bae5d3d6a` instead, the last `master` commit on `2018-03-19` in repo.

2019-02-19 01:08 UTC, aeschright approved these changes
🚀 ⭐️ 🍏

2019-02-19 17:19 UTC, merged