Optional appropriate environ replace
npm/cli pull request #93
Opened 2018-11-09 09:26 UTC by gucong3000

By this PR, we can use a cross-platform configuration items in the `.npmrc` file:
```ini
shell=${GIT_INSTALL_ROOT-}/bin/bash
script-shell=${GIT_INSTALL_ROOT-}/bin/sh
```

2018-12-11 20:29 UTC, aeschright commented
This needs tests and some documentation to explain what the feature is and how it works.

2019-07-02 19:35 UTC, isaacs requested changes
Bug in the `\` handling logic, and definitely needs a test and update to the docs.

2019-07-02 19:35 UTC, isaacs commented on lib/config/core.js
> +      failback = name.slice(failbackMatch.index + 1)
If you have an even number of `\` chars, then this will be the wrong offset. https://gist.github.com/isaacs/c2b12db30a49324325a3781302668408

I recommend writing the failback parsing logic as a new npm module, so that it can get proper tests and documentation.

2020-03-10 16:38 UTC, darcyclarke commented
@gucong3000 appreciate the contribution; That said, this seems to have some caveats to the implementation & looks fairly nuanced in terms of usage. I'm going to close this for now.

2020-03-10 16:38 UTC, closed without merging